### ISSUE TITLE
matcher.knnMatch sometimes gets NoneType as input

### ISSUE THREAD

**Issue by mantfish** [DTUAqua-ObsTek/mosaic-library#4]
Error is:

Traceback (most recent call last):
  File "./mosaic-library/mosaicking/mosaic.py", line 398, in <module>
    main()
  File "/mosaic.py", line 385, in main
    raise err
  File "/mosaic-library/mosaicking/mosaic.py", line 244, in main
    ret, matches = registration.get_matches(des_prev, des, flann, args.min_matches)
  File "/lib/python3.9/site-packages/mosaicking/registration.py", line 16, in get_matches
    matches = matcher.knnMatch(d1.astype(np.float32), d2.astype(np.float32), 2)
AttributeError: 'NoneType' object has no attribute 'astype'

This shouldn't happen because [this section](https://github.com/DTUAqua-ObsTek/mosaic-library/blob/500f6fc229c8c40c9b1c1dc5fa39309ca0267891/mosaicking/mosaic.py#L215-L219) should check the length of detected features, but appears to be invalid.

**Comment by DTUAqua-ObsTek** [comment]
Looks like this can error can be produced when:
1. multiple feature detectors used
2. at least one feature detector does not detect any features
3. the minimum number of features condition is met by the remaining feature detectors

Fixed in #5
